name: Eleventy Build
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build 11ty
        uses: cagov/actions-eleventy@3.1
        with:	
          build_task: build 
          build_eleventy_args: --formats=html,njk --input ./pages --output ./docs	
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          cname: www.oguzh4n.net
