name: Eleventy Build
on:
  push:
    branches:
      - dev
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: cagov/actions-eleventy@v2.0
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
